function renderLicenseBadge(license) {
  if (license) {
    switch (license) {
      case 'Apache 2.0':
        badge = '[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)]';
        break;
      case 'Boost 1.0':
        badge = '[![License](https://img.shields.io/badge/License-Boost%201.0-lightblue.svg)]';
        break;
      case 'BSD 3-Clause':
        badge = '[![License](https://img.shields.io/badge/License-BSD%203--Clause-blue.svg)]';
        break;
      case 'EPL 1.0':
        badge = '[![License](https://img.shields.io/badge/License-EPL%201.0-red.svg)]';
        break;
      case 'GPLv3':
        badge = '[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)]';
        break;
      case 'IPL 1.0':
        badge = '[![License: IPL 1.0](https://img.shields.io/badge/License-IPL%201.0-blue.svg)]';
        break;
      case 'ISC':
        badge = '[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)]';
        break;
      case 'MIT':
        badge = '[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)]';
        break;
      case 'MPL 2.0':
        badge = '[![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg)]';
        break;
      case 'Perl':
        badge = '[![License: Artistic-2.0](https://img.shields.io/badge/License-Perl-0298c3.svg)]';
        break;
    }
    return badge;
  } else {
    return "";
  }
}

function renderLicenseLink(license) {
  if (license) {
    switch (license) {
      case 'Apache 2.0':
        licenseLink = '(https://opensource.org/licenses/Apache-2.0)';
        break;
      case 'Boost 1.0':
        licenseLink = '(https://www.boost.org/LICENSE_1_0.txt)';
        break;
      case 'BSD 3-Clause':
        licenseLink = '(https://opensource.org/licenses/BSD-3-Clause)';
        break;
      case 'EPL 1.0':
        licenseLink = '(https://opensource.org/licenses/EPL-1.0)';
        break;
      case 'GPLv3':
        licenseLink = '(https://www.gnu.org/licenses/gpl-3.0)';
        break;
      case 'IPL 1.0':
        licenseLink = '(https://opensource.org/licenses/IPL-1.0)';
        break;
      case 'ISC':
        licenseLink = '(https://opensource.org/licenses/ISC)';
        break;
      case 'MIT':
        licenseLink = '(https://opensource.org/licenses/MIT)';
        break;
      case 'MPL 2.0':
        licenseLink = '(https://opensource.org/licenses/MPL-2.0)';
        break;
      case 'Perl':
        licenseLink = '(https://opensource.org/licenses/Artistic-2.0)';
        break;
    }
    return licenseLink;
  } else {
    return "";
  }
}

function renderLicenseSection(license) {
  if (license) {
    switch (license) {
      case 'Apache 2.0':
        licenseDescription = 'Licensed under the Apache License, Version 2.0 (the "License") you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.'
        break;
      case 'Boost 1.0':
        licenseDescription = 'Boost Software License - Version 1.0 - August 17th, 2003 Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following: The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
        break;
      case 'BSD 3-Clause':
        licenseDescription = 'Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.'
        break;
      case 'EPL 1.0':
        licenseDescription = 'THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM CONSTITUTES RECIPIENT\'S ACCEPTANCE OF THIS AGREEMENT. Visit the link in the badge to learn more.'
        break;
      case 'GPLv3':
        licenseDescription = 'This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License, along with this program. If not, see https://www.gnu.org/licenses/.'
        break;
      case 'IPL 1.0':
        licenseDescription = 'THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS IBM PUBLIC LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM CONSTITUTES RECIPIENT\'S ACCEPTANCE OF THIS AGREEMENT. Visit the link in the badge to learn more.'
        break;
      case 'ISC':
        licenseDescription = 'Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.'
        break;
      case 'MIT':
        licenseDescription = 'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
        break;
      case 'MPL 2.0':
        licenseDescription = 'Visit the link in the badge to learn more.';
        break;
      case 'Perl':
        licenseDescription = 'Copyright (c) 2000-2006, The Perl Foundation. Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed. Visit the link in the badge to learn more.'
        break;
    }
    return licenseDescription;
  } else {
    return "";
  }
}

function generateMarkdown(data) {
  return `
  ${renderLicenseBadge(data.license)}${renderLicenseLink(data.license)}
  # ${data.appTitle}\n
  ## ${data.appTitle} Description\n
  ${data.appPurpose}\n
  ## Table of Contents\n
  * Using ${data.appTitle}
  * Installing ${data.appTitle}
  * Reporting ${data.appTitle} Issues
  * Contributeing ${data.appTitle}
  * ${data.appTitle} Testing Information
  * ${data.appTitle} Questions
  * ${data.appTitle} License Information\n
  ## Using ${data.appTitle}\n
  ${data.appUsage}\n
  ## Installing ${data.appTitle}\n
  ${data.appInstall}\n
  ## Reporting ${data.appTitle} Issues\n
  ${data.appIssues}\n
  ## Contributing to ${data.appTitle}\n
  ${data.appContributions}\n
  ## ${data.appTitle} Testing Instructions\n
  ${data.appTests}\n
  ## ${data.appTitle} Questions\n
  For any questions, reach out to me at my [GitHub](https://github.com/${data.appGithub}) or at my [email](mailto:${data.appEmail}).\n
  ## ${data.appTitle} License Information\n
  ${renderLicenseSection(data.license)}
`;
}

module.exports = generateMarkdown, renderLicenseBadge, renderLicenseLink, renderLicenseSection;
